backend:
  name: github
  repo: zorpid/Ers-Site
  branch: main
  base_url: https://api.netlify.com
  site_id: 284bbda1-8eaf-47da-a127-e0d2d3109ece


media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
