backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Innehåll"
    files:
      - label: "Hemsida"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Innehåll", name: "body", widget: "markdown" }
